// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADag0HlG-QZmLaId6WQNBPpofpkmoUoek',
    appId: '1:423253647993:web:301f049eeb5fb3e7f5eaa8',
    messagingSenderId: '423253647993',
    projectId: 'mindbloom-81090',
    authDomain: 'mindbloom-81090.firebaseapp.com',
    storageBucket: 'mindbloom-81090.firebasestorage.app',
    measurementId: 'G-CV82W61M2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqYrBknNfKAstq3T_se49tiRDDcf0wq0',
    appId: '1:423253647993:android:1082335fac9d0db1f5eaa8',
    messagingSenderId: '423253647993',
    projectId: 'mindbloom-81090',
    storageBucket: 'mindbloom-81090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaI1DEXyb5-v9AzsGJH9tvYPSQMauGdls',
    appId: '1:423253647993:ios:cc5c07cb0e701914f5eaa8',
    messagingSenderId: '423253647993',
    projectId: 'mindbloom-81090',
    storageBucket: 'mindbloom-81090.firebasestorage.app',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaI1DEXyb5-v9AzsGJH9tvYPSQMauGdls',
    appId: '1:423253647993:ios:cc5c07cb0e701914f5eaa8',
    messagingSenderId: '423253647993',
    projectId: 'mindbloom-81090',
    storageBucket: 'mindbloom-81090.firebasestorage.app',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADag0HlG-QZmLaId6WQNBPpofpkmoUoek',
    appId: '1:423253647993:web:b1600162fbb9032af5eaa8',
    messagingSenderId: '423253647993',
    projectId: 'mindbloom-81090',
    authDomain: 'mindbloom-81090.firebaseapp.com',
    storageBucket: 'mindbloom-81090.firebasestorage.app',
    measurementId: 'G-SJ8L0XD2C2',
  );
}
